export const NAV_LINKS = [
  { name: "Academics", href: "/academics" },
  { name: "About", href: "/about" },
  { name: "Campus Life", href: "/campus-life" },
  { name: "Admission", href: "/admissions" },
  { name: "News", href: "/news" },
  { name: "Contact Us", href: "/contact" },
];

export const UTILITY_LINKS = [
  { name: "Students", href: "/students" },
  { name: "Faculty & Staff", href: "/faculty" },
  { name: "Alumni", href: "/alumni" },
  { name: "Parents", href: "/parents" },
  { name: "Visitors", href: "/visitors" },
];

export const CAMPUS_NEWS = [
  {
    category: "EARTH & CLIMATE",
    title: "New sustainability initiative launches across campus",
    description: "Researchers pioneer an innovative approach to urban sustainability aiming to reduce carbon footprints by 40%.",
    image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&auto=format&fit=crop"
  },
  {
    category: "TECHNOLOGY",
    title: "AI institute announces major breakthrough in machine learning",
    description: "A new algorithm developed by our researchers drastically reduces the energy consumption of large language models.",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop"
  },
  {
    category: "HUMANITIES",
    title: "Rare manuscripts exhibition opens at the central library",
    description: "Discover centuries-old texts that offer unprecedented insights into early modern philosophical thought.",
    image: "https://www.stanford.edu/wp-content/uploads/2023/03/20211117_Elizabeth_Reese_N6A0441-2048x1366.jpg"
  }
];

export const UPCOMING_EVENTS = [
  {
    month: "OCT",
    day: "14",
    title: "Presidential Lecture Series: The Future of Global Health",
    time: "5:30 PM - Memorial Auditorium"
  },
  {
    month: "OCT",
    day: "18",
    title: "Autumn Arts Festival & Symphony Open Air",
    time: "12:00 PM - Main Quad"
  },
  {
    month: "OCT",
    day: "22",
    title: "Engineering Innovation Showcase",
    time: "10:00 AM - Huang Engineering Center"
  },
  {
    month: "NOV",
    day: "02",
    title: "Alumni Homecoming Weekend Kickoff",
    time: "4:00 PM - Alumni Center"
  }
];

export const FOOTER_LINKS = {
  academics: [
    { name: "Undergraduate", href: "/academics/undergrad" },
    { name: "Graduate", href: "/academics/grad" },
    { name: "Professional", href: "/academics/professional" },
  ],
  research: [
    { name: "Centers & Institutes", href: "/research/centers" },
    { name: "Libraries", href: "/research/libraries" },
    { name: "Labs", href: "/research/labs" },
  ],
  about: [
    { name: "History", href: "/about/history" },
    { name: "Leadership", href: "/about/leadership" },
    { name: "Careers", href: "/about/careers" },
  ],
};

export const SITE_INFO = {
  name: "GGSIPU Prototype",
  address: "Sector 16C, Dwarka, New Delhi 110078",
  phone: "650-723-2300",
  email: "info@ipu.ac.in",
};

export const GGSIPU_CONTACTS = [
  {
    id: "vco",
    name: "Office of Vice Chancellor",
    officerName: "Prof. (Dr.) Mahesh Verma",
    designation: "Vice Chancellor",
    phone: "+91-11-25302104, +91-11-25302105",
    fax: "+91-11-28035243",
    email: "vc@ipu.ac.in",
  },
  {
    id: "uss",
    name: "University School of Studies",
    officerName: "",
    designation: "Dean",
    phone: "",
    fax: "",
    email: "",
  },
  {
    id: "registrar",
    name: "Office of Registrar",
    officerName: "Dr. Kamal Pathak",
    designation: "Registrar",
    phone: "+91-11-25302113, +91-11-25302114",
    fax: "+91-11-25302111",
    email: "registrar@ipu.ac.in",
  },
  {
    id: "finance",
    name: "Finance & Accounts Branch",
    officerName: "Sh. Pitambar Behera",
    designation: "Controller of Finance",
    phone: "+91-11-25302197",
    fax: "",
    email: "cof@ipu.ac.in",
  },
  {
    id: "exam",
    name: "Examinations Branch",
    officerName: "Dr. Gulshan Kumar / Dr. S. L. Bhandarkar",
    designation: "COE 1 / COE 2",
    phone: "+91-11-25302252, +91-11-25302263",
    fax: "+91-11-25302248",
    email: "coe@ipu.ac.in",
  },
  {
    id: "placement",
    name: "Centralized Career Guidance and Placement Cell",
    officerName: "Prof. Ashish Payal",
    designation: "Director",
    phone: "011-25302739",
    fax: "",
    email: "cpc@ipu.ac.in, ccgpc.ggsipu@gmail.com",
  },
  {
    id: "library",
    name: "University Information Resources Centre (Library)",
    officerName: "Prof. Lisa P. Lukose",
    designation: "Administrative Head",
    phone: "+91-11-25302218, +91-11-25302219, +91-11-25302221",
    fax: "",
    email: "",
  },
  {
    id: "ceps",
    name: "Centre of Excellence in Pharmaceutical Sciences",
    officerName: "Prof. Promila Gupta",
    designation: "Director",
    phone: "+91-11-25302446",
    fax: "",
    email: "ceps@ipu.ac.in",
  },
  {
    id: "disaster",
    name: "Disaster Management Studies",
    officerName: "Prof. Amarjeet Kaur",
    designation: "Director",
    phone: "011-25302780, 011-25302782, 011-25302783",
    fax: "",
    email: "",
  },
  {
    id: "academic",
    name: "Academic Affairs",
    officerName: "Prof. Shruti Aggarwal",
    designation: "Director",
    phone: "+91-11-25302133",
    fax: "",
    email: "director.acad@ipu.ac.in",
  },
  {
    id: "development",
    name: "Development",
    officerName: "Prof. A.K. Saini",
    designation: "Director",
    phone: "+91-11-25302119",
    fax: "",
    email: "",
  },
  {
    id: "rnd",
    name: "Research & Development Cell",
    officerName: "Prof. Nimisha Sharma",
    designation: "Director",
    phone: "+91-11-25302121, +91-11-25302123",
    fax: "+91-11-25302122",
    email: "drc@ipu.ac.in",
  },
  {
    id: "international",
    name: "International Affairs",
    officerName: "Prof. Gagan Deep Sharma",
    designation: "Director",
    phone: "+91-11-25302126, +91-11-2530125",
    fax: "",
    email: "director.international@ipu.ac.in",
  },
  {
    id: "dsw",
    name: "Students Welfare",
    officerName: "Prof. Meenu Kapoor",
    designation: "Director",
    phone: "+91-11-25302800, +91-11-25302801",
    fax: "",
    email: "dsw@ipu.ac.in",
  },
  {
    id: "iic",
    name: "Industry Interaction Cell",
    officerName: "Prof. A.K. Saini",
    designation: "Director",
    phone: "",
    fax: "",
    email: "director.iic@ipu.ac.in",
  },
  {
    id: "proctor",
    name: "Office of Proctor",
    officerName: "Prof. Anup Singh Beniwal",
    designation: "Proctor",
    phone: "+91-11-25302998",
    fax: "",
    email: "proctor@ipu.ac.in",
  },
  {
    id: "uwd",
    name: "University Works Division",
    officerName: "Sh. Shailesh",
    designation: "Superintending Engineer",
    phone: "+91-11-25302288, +91-11-25302289",
    fax: "+91-11-25302290",
    email: "se.uwd@ipu.ac.in",
  },
  {
    id: "cvo",
    name: "Chief Vigilance Officer",
    officerName: "Dr. Kamal Pathak",
    designation: "CVO",
    phone: "+91-11-25302190",
    fax: "",
    email: "cvo@ipu.ac.in",
  },
  {
    id: "nss",
    name: "NSS Cell",
    officerName: "Prof. Varun Joshi",
    designation: "Programme Coordinator",
    phone: "011-25302369",
    fax: "",
    email: "nsscell@ipu.ac.in",
  },
  {
    id: "ncc",
    name: "NCC Cell",
    officerName: "Prof. Varun Joshi",
    designation: "Programme Coordinator",
    phone: "011-25302369",
    fax: "",
    email: "ncccell@ipu.ac.in",
  },
  {
    id: "uits",
    name: "University IT Services",
    officerName: "Prof. Amit Prakash Singh",
    designation: "Director",
    phone: "011-25302746",
    fax: "",
    email: "",
  },
  {
    id: "hostel",
    name: "University Hostel",
    officerName: "Prof. C. S. Rai",
    designation: "Chief Warden",
    phone: "",
    fax: "",
    email: "",
  },
  {
    id: "academic-branch",
    name: "Academic Branch",
    officerName: "Prof. Udayan Ghose",
    designation: "Director",
    phone: "+91-11-25302152, +91-11-25302154",
    fax: "+91-11-25302158",
    email: "acad.admissions@ipu.ac.in",
  },
  {
    id: "coordination",
    name: "Coordination Branch",
    officerName: "Prof. Rakesh Kumar",
    designation: "Director",
    phone: "+91-11-25302135, +91-11-25302136",
    fax: "",
    email: "coordination@ipu.ac.in",
  },
  {
    id: "rti",
    name: "RTI Branch",
    officerName: "Sh. Naveen Bhardwaj",
    designation: "CPIO",
    phone: "+91-11-25302193",
    fax: "",
    email: "cpio@ipu.ac.in",
  },
  {
    id: "estate",
    name: "Estate Branch",
    officerName: "Dr. Pankaj Agrawal",
    designation: "Dy. Registrar",
    phone: "+91-11-25302245, +91-11-25302247",
    fax: "",
    email: "estate@ipu.ac.in",
  },
  {
    id: "affiliation",
    name: "Affiliation Branch",
    officerName: "Dr. Abha Vermani",
    designation: "Dy. Registrar",
    phone: "+91-11-25302172, +91-11-25302173, +91-11-25302174",
    fax: "",
    email: "affiliation@ipu.ac.in",
  },
  {
    id: "purchase",
    name: "Purchase Branch",
    officerName: "Sh. Dipin Arora",
    designation: "Dy. Registrar",
    phone: "+91-11-25302149, +91-11-25302150",
    fax: "",
    email: "purchase@ipu.ac.in",
  },
  {
    id: "ga",
    name: "General Administration",
    officerName: "Sh. Prabhat Mishra",
    designation: "Incharge",
    phone: "+91-11-25302138, +91-11-25302139",
    fax: "",
    email: "ga@ipu.ac.in",
  },
  {
    id: "stores",
    name: "Central Store",
    officerName: "Sh. Yogesh Bhati",
    designation: "Incharge",
    phone: "+91-11-25302140, +91-11-25302141",
    fax: "",
    email: "central.stores@ipu.ac.in",
  },
  {
    id: "pr",
    name: "Public Relation Section",
    officerName: "Prof. Tanu Dang / Dr. Nalini Ranjan",
    designation: "Media Head / PRO",
    phone: "+91-11-25302170, +91-11-25302171",
    fax: "",
    email: "pro@ipu.ac.in",
  }
];